name: GH Page

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Installing Deps
      run: npm install
      
    # - name: Test
    #   run: npm test

    - name: Build
      run: npm run build

    - name: Deploy GH Page
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true
